// -------------------------------------------------------------------------
//  Copyright © 2021 Province of British Columbia
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------

using System;
using System.Threading.Tasks;

namespace EMBC.ESS.Managers.Submissions
{
    public class EmailTemplate : Template
    {
        public string Subject { get; set; }
        public string Content { get; set; }
    }

    public class EmailTemplateProvider : ITemplateProvider
    {
        public async Task<Template> Get(SubmissionTemplateType template) =>
            await Task.FromResult(template switch
            {
                SubmissionTemplateType.NewAnonymousEvacuationFileSubmission => GetAnonymousnewTemplate(),
                SubmissionTemplateType.NewEvacuationFileSubmission => GetNewTemplate(),
                SubmissionTemplateType.newProfileRegistration => GetRegisterNewTemplate(),
                _ => throw new NotImplementedException($"No template found for {template}")
            });

        private EmailTemplate GetRegisterNewTemplate()
        {
            string emailSubject = "Registration completed successfully";
            string emailBody = @"
<p>This email has been generated by the Emergency Support Services program to confirm your profile has been created within the Evacuee Registration and Assistant(ERA) tool.</p>
<br>
<p>Please use the following link to login to the tool and review your profile information, start an ESS file if required, or review existing ESS file and support information.</p>
<br>
<p>Go to <a href='https://ess.gov.bc.ca'>https://ess.gov.bc.ca</a> and select the 'Already have an account? Log in' link.</p>";

            return new EmailTemplate { Subject = emailSubject, Content = emailBody };
        }

        private EmailTemplate GetNewTemplate()
        {
            string emailSubject = "Registration completed successfully";
            string emailBody = @"
<p>
<p style='font-size: 18pt;color:darkblue;font-weight: bold;'>Submission Complete</p>
<p>
<p>
<p style='font-size: 16pt;color:lightblue;'>Your Emergency Support Services (ESS) File Number is: {fileNumber}</p>
<p>Thank you for submitting your online self-registration.
<p>
<p>
<p style='font-size: 18pt;color:lightblue;font-weight: bold;'>Next Steps</p>
<p>
    <li>Please keep a record of your Emergency Support Services File Number to receive emergency support services that
        can
        be provided up to 72 hours starting from the time connecting in with a local ESS Responder at a Reception
        Centre.
    </li>
</p>
<br>
<p>
    <li>After a need's assessment interview with a local ESS Responder has been completed, supports are provided to
        purchase goods and services if eligible.</li>
</p>
<br>
<p>
    <li>Any goods and services purchased prior to a need’s assessment interview are not eligible for retroactive
        reimbursement.</li>
</p>
<br>
<p>
    <li>If you are under <b>EVACUATION ALERT</b> or <b>DO NOT</b> require emergency serves at this time, no further
        action is required.</li>
</p>
<br>
<p>
    <li>If you are under <b>EVACUATION ORDER</b>, and require emergency supports, proceed to your nearest Reception
        Centre. A list of open Reception Centres can be found at Emergency Info BC.</li>
</p>
<br>
<p>
    <li>If <b>NO</b> nearby Reception Centre is open and immediate action is required, please contact your Local
        Emergency Program for next steps.</li>
</p>
<br>
<p>
    <li>If you have a registered account please use the following link to login to the tool and review and/or edit your
        new ESS File: <a href='https://ess.gov.bc.ca'>https://ess.gov.bc.ca</a> (select the 'Already have an account?
        Log in' link)</li>
</p>";

            return new EmailTemplate { Subject = emailSubject, Content = emailBody };
        }

        private EmailTemplate GetAnonymousnewTemplate()
        {
            string emailSubject = "Registration completed successfully";
            string emailBody = @"
<p>
<p style='font-size: 18pt;color:darkblue;font-weight: bold;'>Submission Complete</p>
<p>
<p>
<p style='font-size: 16pt;color:lightblue;'>Your Emergency Support Services (ESS) File Number is: {fileNumber}
</p>
<p>Thank you for submitting your online self-registration.
<p>
<p>
<p style='font-size: 18pt;color:lightblue;font-weight: bold;'>Next Steps</p>
<p>
    <li>Please keep a record of your Emergency Support Services File Number to receive emergency support services that
        can
        be provided up to 72 hours starting from the time connecting in with a local ESS Responder at a Reception
        Centre.
    </li>
</p>
<br>
<p>
    <li>After a need's assessment interview with a local ESS Responder has been completed, supports are provided to
        purchase goods and services if eligible.</li>
</p>
<br>
<p>
    <li>Any goods and services purchased prior to a need’s assessment interview are not eligible for retroactive
        reimbursement.</li>
</p>
<br>
<p>
    <li>If you are under <b>EVACUATION ALERT</b> or <b>DO NOT</b> require emergency serves at this time, no further
        action is required.</li>
</p>
<br>
<p>
    <li>If you are under <b>EVACUATION ORDER</b>, and require emergency supports, proceed to your nearest Reception
        Centre. A list of open Reception Centres can be found at Emergency Info BC.</li>
</p>
<br>
<p>
    <li>If <b>NO</b> nearby Reception Centre is open and immediate action is required, please contact your Local
        Emergency Program for next steps.</li>
</p>
<br>
<p>
    <li>If you have a registered account please use the following link to login to the tool and review and/or edit your
        new ESS File: <a href='https://ess.gov.bc.ca'>https://ess.gov.bc.ca</a> (select the 'Already have an account?
        Log in' link)</li>
</p>";

            return new EmailTemplate { Subject = emailSubject, Content = emailBody };
        }
    }
}
