// -------------------------------------------------------------------------
//  Copyright © 2020 Province of British Columbia
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using EMBC.Registrants.API.SecurityModule;
using EMBC.Registrants.API.Utils;

namespace EMBC.Registrants.API.ProfilesModule
{
    public interface IProfileManager
    {
        Task<Profile> GetProfileByBcscid(string userId);

        Task<string> SaveProfile(Profile profile);

        Task<IEnumerable<ProfileDataConflict>> GetProfileConflicts(string userId);

        Task DeleteProfile(string userId);

        Task<Profile> GetLoginProfile(string userId);
    }

    public class ProfileManager : IProfileManager
    {
        private readonly IProfileRepository profileRepository;
        private readonly IUserRepository userRepository;
        private readonly IMapper mapper;
        private readonly IEmailSender emailSender;

        public ProfileManager(IProfileRepository profileRepository, IUserRepository userRepository, IMapper mapper, IEmailSender emailSender)
        {
            this.profileRepository = profileRepository;
            this.userRepository = userRepository;
            this.mapper = mapper;
            this.emailSender = emailSender;
        }

        public async Task DeleteProfile(string userId)
        {
            await profileRepository.Delete(userId);
        }

        public async Task<IEnumerable<ProfileDataConflict>> GetProfileConflicts(string userId)
        {
            var user = await userRepository.Read(userId);
            if (user == null) return null;

            var userProfile = mapper.Map<Profile>(user);
            var profile = await profileRepository.Read(user.Id);
            var conflicts = ProfilesConflictDetector.DetectConflicts(profile, userProfile);

            return conflicts.ToArray();
        }

        public async Task<Profile> GetProfileByBcscid(string userId)
        {
            return await profileRepository.Read(userId);
        }

        public async Task<string> SaveProfile(Profile profile)
        {
            if (!await profileRepository.DoesProfileExist(profile.Id))
            {
                await profileRepository.Create(profile);

                // get user by BCServicesCardId
                Profile newProfile = await profileRepository.Read(profile.Id);

                if (profile != null && profile.ContactDetails.Email != null)
                {
                    // Send email notification of new registrant record created
                    EmailAddress registrantEmailAddress = new EmailAddress
                    {
                        Name = profile.PersonalDetails.FirstName + " " + profile.PersonalDetails.LastName,
                        Address = profile.ContactDetails.Email
                    };
                    SendRegistrationNotificationEmail(registrantEmailAddress);
                }
            }
            else
            {
                await profileRepository.Update(profile);
            }
            return profile.Id;
        }

        public async Task<Profile> GetLoginProfile(string userId)
        {
            var user = await userRepository.Read(userId);
            if (user == null) return null;
            return mapper.Map<Profile>(user);
        }

        /// <summary>
        /// Sends a notification email to a verified Registrant after they register their profile
        /// </summary>
        /// <param name="toAddress">Registrant's Email Address</param>
        private void SendRegistrationNotificationEmail(EmailAddress toAddress)
        {
            System.Collections.Generic.List<EmailAddress> toList = new System.Collections.Generic.List<EmailAddress> { toAddress };
            string emailSubject = "Registration completed successfully";
            string emailBody = $@"
<p>This email has been generated by the Emergency Support Services program to confirm your profile has been created within the Evacuee Registration and Assistant(ERA) tool.</p>
<br>
<p>Please use the following link to login to the tool and review your profile information, start an ESS file if required, or review existing ESS file and support information.</p>
<br>
<p>Go to <a href='https://ess.gov.bc.ca'>https://ess.gov.bc.ca</a> and select the 'Already have an account? Log in' link.</p>";

            EmailMessage emailMessage = new EmailMessage(toList, emailSubject, emailBody);
            emailSender.Send(emailMessage);
        }
    }
}
