kind: Template
apiVersion: v1
metadata:
  name: suppliers-portal-template

parameters:
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Dynamics ADFS token endpoint
    name: OAUTH_ENDPOINT
    required: true
  - description: Dynamics ADFS client ID
    name: OAUTH_CLIENT_ID
    required: true
  - description: Dynamics ADFS client secret
    name: OAUTH_CLIENT_SECRET
    required: true
  - description: Dynamics ADFS resource name
    name: OAUTH_RESOURCE
    required: true
  - description: Dynamics API endpoint
    name: DYNAMICS_ENDPOINT
    required: true
  - description: Dynamics service account domain
    name: DYNAMICS_SERVICE_ACCOUNT_DOMAIN
    required: true
  - description: Dynamics service account name
    name: OAUTH_DYNAMICS_SERVICE_ACCOUNT_NAME
    required: true
  - description: Dynamics service account password
    name: OAUTH_DYNAMICS_SERVICE_ACCOUNT_PASSWORD
    required: true
  - description: Submission persistant directory
    name: SUBMISSIONS_STORAGE_DIR
    required: true
    value: /submissions
  - description: Dynanics lookup cache persistant directory
    name: DYNAMICS_LISTS_CACHE_DIR
    value: /lookup_cache
  - description: Dynanics lookup cache frequency refresh in minutes
    name: DYNAMICS_LISTS_CACHE_UPDATE_FREQUENCY
    value: "60"
  - description: Reverse proxy known network
    name: KNOWN_NETWORKS
    value: ::ffff:172.51.0.0/16
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-suppliers-api-config
      labels:
        app: ${APP_NAME}-suppliers-portal
    data:
      Dynamics__ADFS__OAuth2TokenEndpoint: ${OAUTH_ENDPOINT}
      Dynamics__DynamicsApiEndpoint: ${DYNAMICS_ENDPOINT}
      Submission_Storage_Path: ${SUBMISSIONS_STORAGE_DIR}
      Dynamics__Cache__CachePath: ${DYNAMICS_LISTS_CACHE_DIR}
      Dynamics__Cache__UpdateFrequency: ${DYNAMICS_LISTS_CACHE_UPDATE_FREQUENCY}
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"
  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-suppliers-api-secrets
      labels:
        app: ${APP_NAME}-suppliers-portal
    stringData:
      Dynamics__ADFS__ClientId: ${OAUTH_CLIENT_ID}
      Dynamics__ADFS__ClientSecret: ${OAUTH_CLIENT_SECRET}
      Dynamics__ADFS__ResourceName: ${OAUTH_RESOURCE}
      Dynamics__ADFS__serviceAccountDomain: ${DYNAMICS_SERVICE_ACCOUNT_DOMAIN}
      Dynamics__ADFS__serviceAccountName: ${OAUTH_DYNAMICS_SERVICE_ACCOUNT_NAME}
      Dynamics__ADFS__serviceAccountPassword: ${OAUTH_DYNAMICS_SERVICE_ACCOUNT_PASSWORD}
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-suppliers-portal
      name: ${APP_NAME}-suppliers-portal-api
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-suppliers-portal-api
      type: ClusterIP
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-suppliers-portal
      name: ${APP_NAME}-suppliers-portal-ui
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${APP_NAME}-suppliers-portal-ui
      type: ClusterIP
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-suppliers-portal
      name: ${APP_NAME}-suppliers-portal-api
    spec:
      host: ${APP_NAME}-embc-suppliers.pathfinder.gov.bc.ca
      path: /api
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-suppliers-portal-api
        weight: 100
      wildcardPolicy: None
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-suppliers-portal
      name: ${APP_NAME}-suppliers-portal-ui
    spec:
      host: ${APP_NAME}-embc-suppliers.pathfinder.gov.bc.ca
      path: /
      port:
        targetPort: 2015-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-suppliers-portal-ui
        weight: 100
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-suppliers-portal
      name: ${APP_NAME}-suppliers-portal-api
    spec:
      replicas: 2
      selector:
        app: ${APP_NAME}-suppliers-portal
        deploymentconfig: ${APP_NAME}-suppliers-portal-api
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-suppliers-portal
            deploymentconfig: ${APP_NAME}-suppliers-portal-api
        spec:
          containers:
            - name: suppliers-portal-api
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-suppliers-api-config
                - secretRef:
                    name: ${APP_NAME}-suppliers-api-secrets
              image: docker-registry.default.svc:5000/pbiizm-tools/suppliers-portal-api:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: ${SUBMISSIONS_STORAGE_DIR}
                  name: submissions-storage
                - mountPath: /dpkeys
                  name: dp-keys
                - mountPath: ${DYNAMICS_LISTS_CACHE_DIR}
                  name: lists-cache
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: submissions-storage
              persistentVolumeClaim:
                claimName: ${APP_NAME}-suppliers-submissions
            - name: dp-keys
              persistentVolumeClaim:
                claimName: ${APP_NAME}-suppliers-key-ring
            - name: lists-cache
              persistentVolumeClaim:
                claimName: ${APP_NAME}-suppliers-cache
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - suppliers-portal-api
            from:
              kind: ImageStreamTag
              name: suppliers-portal-api:${TAG}
              namespace: pbiizm-tools
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-suppliers-portal
      name: ${APP_NAME}-suppliers-portal-ui
    spec:
      replicas: 2
      selector:
        app: ${APP_NAME}-suppliers-portal
        deploymentconfig: ${APP_NAME}-suppliers-portal-ui
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-suppliers-portal
            deploymentconfig: ${APP_NAME}-suppliers-portal-ui
        spec:
          containers:
            - name: suppliers-portal-ui
              image: docker-registry.default.svc:5000/pbiizm-tools/suppliers-portal-ui:${TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - suppliers-portal-ui
            from:
              kind: ImageStreamTag
              name: suppliers-portal-ui:${TAG}
              namespace: pbiizm-tools
  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: "${APP_NAME}-suppliers-submissions"
      labels:
        app: ${APP_NAME}-suppliers-portal
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "1Gi"
  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: "${APP_NAME}-suppliers-key-ring"
      labels:
        app: ${APP_NAME}-suppliers-portal
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"
  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: "${APP_NAME}-suppliers-cache"
      labels:
        app: ${APP_NAME}-suppliers-portal
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"
