kind: Template
apiVersion: v1
metadata:
  name: responders-portal-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Reverse proxy known network
    name: KNOWN_NETWORKS
    value: ::ffff:10.97.0.0/16
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging
  - description: ESS backend url
    name: BACKEND_URL
    required: true
  - description: ESS backend allow invalid server cert
    name: BACKEND_ALLOW_INVALID_CERT
    value: "false"
  - description: JWT metadata url
    name: JWT_METADATA_URL
    required: true
  - description: JWT audience
    name: JWT_AUDIENCE
    required: true
  - description: OIDC issuer
    name: OIDC_ISSUER
    required: true
  - description: OIDC client ID
    name: OIDC_CLIENTID
    required: true
  - description: REDIS Service connection string
    name: REDIS_CONNECTIONSTRING
    required: false

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-responders-api-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"
      BACKEND__URL: ${BACKEND_URL}
      BACKEND__ALLOWINVALIDSERVERCERTIFICATE: ${BACKEND_ALLOW_INVALID_CERT}
      JWT__METADATAADDRESS: ${JWT_METADATA_URL}
      JWT__AUDIENCE: ${JWT_AUDIENCE}
      OIDC__ISSUER: ${OIDC_ISSUER}
      OIDC__CLIENTID: ${OIDC_CLIENTID}

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-responders-api-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:
      REDIS_CONNECTIONSTRING: ${REDIS_CONNECTIONSTRING}

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-responders-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-responders-portal-api
      type: ClusterIP

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-responders-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${APP_NAME}-responders-portal-ui
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-responders-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${APP_NAME}-embc-responders.apps.silver.devops.gov.bc.ca
      path: /api
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-responders-portal-api
        weight: 100
      wildcardPolicy: None

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-responders-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${APP_NAME}-embc-responders.apps.silver.devops.gov.bc.ca
      path: /
      port:
        targetPort: 2015-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-responders-portal-ui
        weight: 100

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-responders-portal
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-responders-portal
      ingress:
        - ports:
            - protocol: TCP
              port: 2015
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-responders-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-responders-portal-api
      strategy:
        activeDeadlineSeconds: 21600
        resources:
          limits:
            cpu: 15m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        rollingParams:
          intervalSeconds: 1
          maxSurge: 50%
          maxUnavailable: 50%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-responders-portal
            role: api
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-responders-portal-api
        spec:
          containers:
            - name: responders-portal-api
              resources:
                limits:
                  cpu: 150m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              env:
                - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
                  value: "/ssl/tls.crt"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-responders-api-config
                - secretRef:
                    name: ${APP_NAME}-responders-api-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/responders-portal-api:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dpkeys
                  name: dp-keys
                - mountPath: /ssl
                  name: ssl
                  readonly: true
              livenessProbe:
                httpGet:
                  path: /hc/live
                  port: 8080
              startupProbe:
                httpGet:
                  path: /hc/startup
                  port: 8080
              readinessProbe:
                httpGet:
                  path: /hc/ready
                  port: 8080
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp-keys
              persistentVolumeClaim:
                claimName: ${APP_NAME}-responders-key-ring
            - name: ssl
              secret:
                secretName: ${APP_NAME}-ess-backend-ssl
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - responders-portal-api
            from:
              kind: ImageStreamTag
              name: responders-portal-api:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-responders-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-responders-portal-ui
      strategy:
        activeDeadlineSeconds: 21600
        resources:
          limits:
            cpu: 15m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        rollingParams:
          intervalSeconds: 1
          maxSurge: 50%
          maxUnavailable: 50%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-responders-portal
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-responders-portal-ui
        spec:
          containers:
            - name: responders-portal-ui
              resources:
                limits:
                  cpu: 50m
                  memory: 64Mi
                requests:
                  cpu: 25m
                  memory: 32Mi
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/responders-portal-ui:${TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 2015
                  protocol: TCP
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              livenessProbe:
                httpGet:
                  path: /
                  port: 2015
              startupProbe:
                httpGet:
                  path: /
                  port: 2015
              readinessProbe:
                httpGet:
                  path: /
                  port: 2015
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - responders-portal-ui
            from:
              kind: ImageStreamTag
              name: responders-portal-ui:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-responders-key-ring
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-responders-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"
