/* tslint:disable */
/* eslint-disable */

/**
 * A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
 */
export interface ProblemDetails {

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: null | string;

  /**
   * Gets the IDictionary`2 for extension members.
   *
   * Problem type definitions MAY extend the problem details object with additional members. Extension members appear in the same namespace as
   * other members of a problem type.
   */
  extensions?: null | { [key: string]: any };

  /**
   * A URI reference that identifies the specific occurrence of the problem.It may or may not yield further information if dereferenced.
   */
  instance?: null | string;

  /**
   * The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
   */
  status?: null | number;

  /**
   * A short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
   * of the problem, except for purposes of localization(e.g., using proactive content negotiation;
   * see[RFC7231], Section 3.4).
   */
  title?: null | string;

  /**
   * A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
   * dereferenced, it provide human-readable documentation for the problem type
   * (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be
   * "about:blank".
   */
  type?: null | string;

  [key: string]: any | null | number | string | undefined | { [key: string]: any };
}
