kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ess-backend-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging
  - name: DYNAMICS_OAUTH_ENDPOINT
    required: true
  - description: Dynamics ADFS client ID
    name: DYNAMICS_OAUTH_CLIENT_ID
    required: true
  - description: Dynamics ADFS client secret
    name: DYNAMICS_OAUTH_CLIENT_SECRET
    required: true
  - description: Dynamics ADFS resource name
    name: DYNAMICS_OAUTH_RESOURCE
    required: true
  - description: Dynamics API endpoint
    name: DYNAMICS_ENDPOINT
    required: true
  - description: Dynamics entities base URI
    name: DYNAMICS_URI
    required: true
  - description: Dynamics service account domain
    name: DYNAMICS_SERVICE_ACCOUNT_DOMAIN
    required: true
  - description: Dynamics service account name
    name: DYNAMICS_SERVICE_ACCOUNT_NAME
    required: true
  - description: Dynamics service account password
    name: DYNAMICS_SERVICE_ACCOUNT_PASSWORD
    required: true
  - description: SMTP Server
    name: SMTP_SERVER
    required: true
  - description: REDIS Service connection string
    name: REDIS_CONNECTIONSTRING
    required: false
  - description: registrants portal base url
    name: REGISTRANTS_PORTAL_BASE_URL
    required: false
  - description: splunk url
    name: SPLUNK_URL
    required: false
  - description: splunk token
    name: SPLUNK_TOKEN
    required: false
    
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-ess-backend-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-ess-backend
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      APP_NAME: ${APP_NAME}-ess-backend
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys/${APP_NAME}-ess-backend"
      Dynamics__ADFS__OAuth2TokenEndpoint: ${DYNAMICS_OAUTH_ENDPOINT}
      Dynamics__DynamicsApiEndpoint: ${DYNAMICS_ENDPOINT}
      Dynamics__DynamicsApiBaseUri: ${DYNAMICS_URI}
      notifications__email__smtpserver: ${SMTP_SERVER}
      pdfGenerator__url: dns:///${APP_NAME}-pdf-generator:2020
      pdfGenerator__allowInvalidServerCertificate: "true"
      REGISTRANTS_PORTAL_BASE_URL: ${REGISTRANTS_PORTAL_BASE_URL}

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-ess-backend-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-ess-backend
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:
      Dynamics__ADFS__ClientId: ${DYNAMICS_OAUTH_CLIENT_ID}
      Dynamics__ADFS__ClientSecret: ${DYNAMICS_OAUTH_CLIENT_SECRET}
      Dynamics__ADFS__ResourceName: ${DYNAMICS_OAUTH_RESOURCE}
      Dynamics__ADFS__serviceAccountDomain: ${DYNAMICS_SERVICE_ACCOUNT_DOMAIN}
      Dynamics__ADFS__serviceAccountName: ${DYNAMICS_SERVICE_ACCOUNT_NAME}
      Dynamics__ADFS__serviceAccountPassword: ${DYNAMICS_SERVICE_ACCOUNT_PASSWORD}
      REDIS_CONNECTIONSTRING: ${REDIS_CONNECTIONSTRING}
      SPLUNK_URL: ${SPLUNK_URL}
      SPLUNK_TOKEN: ${SPLUNK_TOKEN}

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-ess-backend
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-ess-backend
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: ${APP_NAME}-ess-backend-ssl
    spec:
      ports:
        - name: 2020-tcp
          port: 2020
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-ess-backend
      type: ClusterIP

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-ess-backend
      labels:
        app: ${APP_NAME}-ess-backend
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-ess-backend
      policyTypes:
        - Ingress
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/part-of: ${APP_NAME}
                  role: api
          ports:
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-ess-backend
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-ess-backend
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-ess-backend
      strategy:
        resources:
          limits:
            cpu: 15m
            memory: 64Mi
          requests:
            cpu: 5m
            memory: 32Mi
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-ess-backend
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-ess-backend
            role: backend
        spec:
          containers:
            - name: ess-backend
              resources:
                limits:
                  cpu: 150m
                  memory: 512Mi
                requests:
                  cpu: 50m
                  memory: 256Mi
              env:
                - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
                  value: "/ssl/tls.crt"
                - name: "ASPNETCORE_Kestrel__Certificates__Default__KeyPath"
                  value: "/ssl/tls.key"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-ess-backend-config
                - secretRef:
                    name: ${APP_NAME}-ess-backend-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/ess-backend:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dpkeys
                  name: dp
                - mountPath: /ssl
                  name: ssl
                  readonly: true
              livenessProbe:
                httpGet:
                  scheme: HTTPS
                  path: /hc/live
                  port: 8080
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 5
              startupProbe:
                httpGet:
                  scheme: HTTPS
                  path: /hc/startup
                  port: 8080
                initialDelaySeconds: 15
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 5
              readinessProbe:
                httpGet:
                  scheme: HTTPS
                  path: /hc/ready
                  port: 8080
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 5
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp
              persistentVolumeClaim:
                claimName: ${APP_NAME}-data-protection
            - name: ssl
              secret:
                secretName: ${APP_NAME}-ess-backend-ssl
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ess-backend
            from:
              kind: ImageStreamTag
              name: ess-backend:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v2beta2
    metadata:
      name: ${APP_NAME}-ess-backend-has
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-ess-backend
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${APP_NAME}-ess-backend
        apiVersion: apps.openshift.io/v1
      minReplicas: 3
      maxReplicas: 12
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 150
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 125

  # pvc shared with all .net pods for data protection keys
  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-data-protection
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "256Mi"
