kind: Template
apiVersion: v1
metadata:
  name: cas-payment-interface build config template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: dotnet-31
      namespace: ${NAMESPACE_PREFIX}-tools
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          annotations: null
          from:
            kind: DockerImage
            name: registry.access.redhat.com/ubi8/dotnet-31
          generation: 2
          importPolicy: {}
          referencePolicy:
            type: Source

  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: cas-interface-service-build
      namespace: ${NAMESPACE_PREFIX}-tools
      labels:
        app: cas-interface-service
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "cas-interface-service:latest"
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 1Gi
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "dotnet-31:latest"
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: CASInterfaceService/cas-interface-service.csproj
          forcePull: true
      postCommit: {}
      source:
        type: Git
        git:
          uri: "https://github.com/bcgov/cas-payment-interface"
          ref: master
      triggers:
        - type: ConfigChange
        - type: GitHub
          github:
            secretReference:
              name: webhook
      runPolicy: Serial
