kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: registrants-portal-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Reverse proxy known network
    name: KNOWN_NETWORKS
    value: ::ffff:10.97.0.0/16
  - description: ASPNET runtime environment (Development|Staging|Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging
  - description: ESS backend url
    name: BACKEND_URL
    required: true
  - description: ESS backend allow invalid server cert
    name: BACKEND_ALLOW_INVALID_CERT
    value: "false"
  - description: REDIS Service connection string
    name: REDIS_CONNECTIONSTRING
    required: false
  - description: Oauth/oidc server url
    name: OAUTH_AUTHORITY
    required: true
  - description: Oauth server client id
    name: OAUTH_API_CLIENTID
    required: true
  - description: Oauth server client secret
    name: OAUTH_API_CLIENTSECRET
    required: true
  - description: registrants portal client id
    name: OAUTH_UI_CLIENTID
    required: true
  - description: banner title text
    name: BANNER_TITLE
    required: false
  - description: banner sub title text
    name: BANNER_SUBTITLE
    required: false
  - description: color of environment info banner
    name: BANNER_COLOR
    required: false
  - description: session timeout
    name: TIMEOUT_MINUTES
    required: false
  - description: time warning message will display
    name: TIMEOUT_WARNINGDURATION
    required: false
  - description: splunk url
    name: SPLUNK_URL
    required: false
  - description: splunk token
    name: SPLUNK_TOKEN
    required: false

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-registrants-api-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      APP_NAME: ${APP_NAME}-registrants-portal
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys/${APP_NAME}-registrants-portal"
      app__knownNetwork: ${KNOWN_NETWORKS}
      messaging__url: ${BACKEND_URL}
      messaging__allowInvalidServerCertificate: ${BACKEND_ALLOW_INVALID_CERT}
      auth__introspection__authority: ${OAUTH_AUTHORITY}
      auth__jwt__authority: ${OAUTH_AUTHORITY}
      auth__oidc__issuer: ${OAUTH_AUTHORITY}
      TIMEOUT__MINUTES: ${TIMEOUT_MINUTES}
      TIMEOUT__WARNINGDURATION: ${TIMEOUT_WARNINGDURATION}

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-registrants-api-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:
      auth__introspection__clientid: ${OAUTH_API_CLIENTID}
      auth__introspection__clientSecret: ${OAUTH_API_CLIENTSECRET}
      auth__oidc__clientid: ${OAUTH_UI_CLIENTID}
      REDIS_CONNECTIONSTRING: ${REDIS_CONNECTIONSTRING}
      SPLUNK_URL: ${SPLUNK_URL}
      SPLUNK_TOKEN: ${SPLUNK_TOKEN}

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-registrants-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-registrants-portal-api
      type: ClusterIP

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-registrants-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${APP_NAME}-registrants-portal-ui
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      annotations:
        haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
        haproxy.router.openshift.io/timeout: 120s
        haproxy.router.openshift.io/balance: leastconn
      name: ${APP_NAME}-era-registrants-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${APP_NAME}-era-registrants.apps.silver.devops.gov.bc.ca
      path: /api
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-registrants-portal-api
        weight: 100
      wildcardPolicy: None

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      annotations:
        haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
        haproxy.router.openshift.io/balance: leastconn
      name: ${APP_NAME}-era-registrants-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${APP_NAME}-era-registrants.apps.silver.devops.gov.bc.ca
      path: /
      port:
        targetPort: 2015-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-registrants-portal-ui
        weight: 100

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-registrants-portal
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-registrants-portal
      ingress:
        - ports:
            - protocol: TCP
              port: 2015
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-registrants-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      revisionHistoryLimit: 2
      selector:
        deploymentconfig: ${APP_NAME}-registrants-portal-api
      strategy:
        resources:
          limits:
            cpu: 15m
            memory: 64Mi
          requests:
            cpu: 5m
            memory: 32Mi
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-registrants-portal
            role: api
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-registrants-portal-api
        spec:
          containers:
            - resources:
                limits:
                  cpu: 50m
                  memory: 256Mi
                requests:
                  cpu: 25m
                  memory: 128Mi
              name: registrants-portal-api
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-registrants-api-config
                - secretRef:
                    name: ${APP_NAME}-registrants-api-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/registrants-portal-api:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dpkeys
                  name: dp
              livenessProbe:
                httpGet:
                  path: /hc/live
                  port: 8080
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              startupProbe:
                httpGet:
                  path: /hc/startup
                  port: 8080
                initialDelaySeconds: 15
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 5
              readinessProbe:
                httpGet:
                  path: /hc/ready
                  port: 8080
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp
              persistentVolumeClaim:
                claimName: ${APP_NAME}-data-protection #defined in ess backend template
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - registrants-portal-api
            from:
              kind: ImageStreamTag
              name: registrants-portal-api:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v2beta2
    metadata:
      name: ${APP_NAME}-registrants-portal-api-has
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-registrants-portal-api
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${APP_NAME}-registrants-portal-api
        apiVersion: apps.openshift.io/v1
      minReplicas: 3
      maxReplicas: 6
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 150
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 150

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${APP_NAME}-registrants-env
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    data:
      info.json: |
        { "envName": "${ENV}",
        "bannerTitle": "${BANNER_TITLE}",
        "bannerSubTitle": "${BANNER_SUBTITLE}",
        "bannerColor": "${BANNER_COLOR}" }

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-registrants-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-registrants-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      revisionHistoryLimit: 2
      selector:
        deploymentconfig: ${APP_NAME}-registrants-portal-ui
      strategy:
        resources:
          limits:
            cpu: 10m
            memory: 48Mi
          requests:
            cpu: 5m
            memory: 24Mi
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-registrants-portal
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-registrants-portal-ui
        spec:
          containers:
            - name: registrants-portal-ui
              resources:
                limits:
                  cpu: 15m
                  memory: 64Mi
                requests:
                  cpu: 5m
                  memory: 32Mi
              env:
                - name: API_URL
                  value: ${APP_NAME}-registrants-portal-api:8080
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/registrants-portal-ui:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - name: env
                  mountPath: /site/env
                  readOnly: true 
              ports:
                - containerPort: 2015
                  protocol: TCP
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              livenessProbe:
                httpGet:
                  path: /
                  port: 2016
              startupProbe:
                httpGet:
                  path: /
                  port: 2016
              readinessProbe:
                httpGet:
                  path: /
                  port: 2016
          volumes:
            - name: env
              configMap:
                name: ${APP_NAME}-registrants-env
                defaultMode: 0755
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - registrants-portal-ui
            from:
              kind: ImageStreamTag
              name: registrants-portal-ui:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v2beta2
    metadata:
      name: ${APP_NAME}-registrants-portal-ui-has
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-registrants-portal-ui
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${APP_NAME}-registrants-portal-ui
        apiVersion: apps.openshift.io/v1
      minReplicas: 3
      maxReplicas: 5
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 150
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 150
