name: cd-registrants-portal-ui

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
    paths:
      - "registrants/src/UI/**"
      - ".github/workflows/cd-registrants-portal-ui.yml"
env:
  IMAGE_NAME: registrants-portal-ui
  IMAGE_ID: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}/registrants-portal-ui

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.OCP4_PASSWORD  }}" | docker login ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }} -u ${{ secrets.OCP4_USERNAME }} --password-stdin

      - name: Pull image
        run: docker pull $IMAGE_ID || true

      - name: Build image
        working-directory: ./registrants/src/UI
        run: |
          # Get latest version from tag
          TAG=${{ steps.tag_version.outputs.new_tag }}
          tar -czh . | docker build --tag $IMAGE_ID:temp --cache-from=$IMAGE_ID --build-arg VERSION=$TAG -
          
      - name: Push image
        run: |
          # Get latest version from tag
          TAG=${{ steps.tag_version.outputs.new_tag }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo TAG=${{ steps.tag_version.outputs.new_tag }}
          docker tag $IMAGE_ID:temp $IMAGE_ID:$VERSION
          docker tag $IMAGE_ID:temp $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$TAG