name: ci-ess-backend

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "src/**"
      - "!src/*.API/**"
      - "!src/*.UI/**"
      - "!src/build/**"
      - "src/build/ESS/**"
      - ".github/workflows/ci-ess-backend.yml"

env:
  IMAGE_NAME: ess-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: ./src
        run: tar -czh . | docker build -f ./build/ESS/ESS.Dockerfile --tag $IMAGE_NAME -
