name: ci-ess-backend

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "ess/src/API/**"
      - ".github/workflows/ci-ess-backend.yml"

env:
  IMAGE_NAME: ess-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: ./ess/src/API
        run: tar -czh . | docker build --tag $IMAGE_NAME -
