name: ci-pdf-generator

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "src/EMBC.PDFGenerator/**"
      - "src/EMBC.Tests.Unit.PDFGenerator/**"
      - "!src/build/**"
      - "src/build/PdfGenerator/**"
      - ".github/workflows/ci-pdf-generator.yml"

env:
  IMAGE_NAME: pdf-generator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: ./src
        run: docker build . --file build/PdfGenerator/PdfGenerator.Dockerfile --tag $IMAGE_NAME
