name: ci-registrants-portal-api

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "registrants/src/API/**"
      - "shared/src/**"
      - ".github/workflows/ci-registrants-portal-api.yml"

env:
  IMAGE_NAME: registrants-portal-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ./registrants/src/API
        run: tar -czh . | docker build --tag $IMAGE_NAME -
