# This is a basic workflow to help you get started with Actions

name: OWASP Zap scan

on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  responders-scan:
      runs-on: ubuntu-latest
      name: Scan Responders Portal
      steps:
      - name: UI
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://era-responders-dev.apps.silver.devops.gov.bc.ca'
          issue_title: 'ZAP report for responders-portal-ui'
      - name: API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          target: 'https://era-responders-dev.apps.silver.devops.gov.bc.ca/api'
          issue_title: 'ZAP report for responders-portal-api'
  
  registrants-scan:
      runs-on: ubuntu-latest
      name: Scan Registrants Portal
      steps:
      - name: UI
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://era-evacuees-dev.apps.silver.devops.gov.bc.ca'
          issue_title: 'ZAP report for registrants-portal-ui'
      - name: API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          target: 'https://era-evacuees-dev.apps.silver.devops.gov.bc.ca/api'
          issue_title: 'ZAP report for registrants-portal-api'

  suppliers-scan:
      runs-on: ubuntu-latest
      name: Scan Suppliers Portal
      steps:
      - name: UI
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://era-suppliers-dev.apps.silver.devops.gov.bc.ca'
          issue_title: 'ZAP report for suppliers-portal-ui'
      - name: API
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          target: 'https://era-suppliers-dev.apps.silver.devops.gov.bc.ca/api'
          issue_title: 'ZAP report for suppliers-portal-api'

  oauth-server:
      runs-on: ubuntu-latest
      name: Scan OAuth Server
      steps:
      - name: Server
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://era-oauth-dev.apps.silver.devops.gov.bc.ca'
          issue_title: 'ZAP report for oauth-server'
