name: Sonar scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * Mon'
    
jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8'

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
